export default
{
  resultCode: '0',
  resultMsg: '成功',
  resultObject: {
    commonAttr: {
      commonAttrList: [
        {
          attrValueTypeId: 'ASC',
          cname: '联系人',
          isNull: 'T',
          colspan: '1',
          fieldName: 'contact_info',
          isEdit: 'T',
          orderId: '1',
          value: '肖旭章 17787299324',
          valueDesc: '肖旭章 17787299324',
        },
        {
          attrValueTypeId: 'ASO',
          cname: '经办人',
          colspan: '1',
          fieldName: 'handler_cust',
          isEdit: 'T',
          isNull: 'F',
          orderId: '3',
          pageUrl: 'test',
        },
        {
          attrValueTypeId: 'ACC',
          cname: '账户',
          colspan: '1',
          fieldName: 'acct_id',
          isEdit: 'T',
          isNull: 'F',
          orderId: '4',
          valueDesc: 'null',
        },
        {
          attrValueTypeId: '98M',
          cname: '促销人',
          colspan: '1',
          fieldName: 'dev_person_info',
          isEdit: 'T',
          isNull: 'F',
          orderId: '4',
        },
        {
          attrValueTypeId: '98D',
          cname: '选号码',
          colspan: '1',
          fieldName: 'dev_person_info',
          isEdit: 'T',
          isNull: 'F',
          orderId: '4',
        },
        {
          attrValueTypeId: '98C',
          cname: '备注信息',
          colspan: '3',
          fieldName: 'remark',
          isEdit: 'T',
          isNull: 'T',
          orderId: '6',
        },
      ],
      isShow: 'T',
      moduleId: '5',
      moduleName: '公共信息',
      orderId: '1',
    },
    offer: {
      isShow: 'T',
      moduleId: '1',
      moduleName: '套餐组件',
      offerInstList: [
        {
          offerId: '10036165',
          offerInstId: '122344',
          offerMember: [
            {
              currentNum: '2',
              maxNum: '11',
              memberName: '手机',
            },
          ],
          offerName: '乐享4G399元-主套餐',
          offerSysType: '1000',
          offerType: '11',
        },
      ],
      orderId: '1',
    },
    product: [
      {
        isShow: 'T',
        moduleId: '2',
        moduleName: '手机',
        orderId: '1',
        prodFuncType: '101',
        prodId: '208511296',
        prodMaxNum: '11',
        prodName: '手机',
        prodRole: [
          {
            deleteFlag: 'false',
            isShow: 'T',
            maxNum: '1',
            minNum: '1',
            mktRes: {
              isShow: 'F',
              moduleId: '9',
              moduleName: '终端组件',
              orderId: '1',
            },
            moduleId: '3',
            moduleName: '移动电话',
            orderId: '1',
            prodAttr: {
              prodAttrList: [
                {
                  attrId: '992075366',
                  attrLength: '255',
                  attrValueTypeId: '98M',
                  cname: '预存款充值',
                  colspan: '1',
                  fieldName: 'attrib_32',
                  isEdit: 'C',
                  isMake: 'T',
                  isNull: 'T',
                  orderId: '12',
                  showType: 'D',
                  tableName: 'prod_inst_ext',
                },
                {
                  attrId: '9998066',
                  attrLength: '255',
                  attrValueTypeId: '98M',
                  cname: '关联产品',
                  colspan: '3',
                  fieldName: 'prod_inst_rela_attr',
                  ifDefaultValue: 'N',
                  isEdit: 'T',
                  isMake: 'C',
                  isNull: 'T',
                  orderId: '270',
                  showType: 'D',
                  tableName: 'prod_inst',
                },
                {
                  attrId: '1020161',
                  attrLength: '100',
                  attrValueTypeId: '98A',
                  cname: '是否开通信控',
                  defaultValue: '2',
                  fieldName: 'attrib_26',
                  ifDefaultValue: 'T',
                  isEdit: 'T',
                  isMake: 'T',
                  isNull: 'T',
                  orderId: '130',
                  showType: 'M',
                  tableName: 'prod_inst_ext',
                },
                {
                  attrId: '1351001',
                  attrLength: '100',
                  attrValueTypeId: '98A',
                  cname: '成品卡批开状态',
                  fieldName: 'attrib_40',
                  ifDefaultValue: 'N',
                  isEdit: 'T',
                  isMake: 'F',
                  isNull: 'T',
                  orderId: '2',
                  showType: 'M',
                  tableName: 'prod_inst_ext',
                },
                {
                  attrId: '690000311',
                  attrLength: '10000',
                  attrValueTypeId: '98M',
                  cname: '扩展产品',
                  colspan: '4',
                  fieldName: 'sub_prod_inst_attr',
                  isEdit: 'T',
                  isMake: 'K',
                  isNull: 'T',
                  orderId: '72',
                  showType: 'M',
                  tableName: 'prod_inst',
                },
                {
                  attrId: '1413001',
                  attrLength: '100',
                  attrValueTypeId: '98A',
                  cname: '4G用户标识',
                  defaultValue: '0',
                  fieldName: 'attrib_19',
                  ifDefaultValue: 'F',
                  isEdit: 'T',
                  isMake: 'F',
                  isNull: 'F',
                  orderId: '148',
                  showType: 'M',
                  tableName: 'prod_inst_ext',
                },
                {
                  attrId: '692303202',
                  attrLength: '10',
                  attrValueTypeId: '98A',
                  cname: '是否准预',
                  defaultValue: '2000',
                  fieldName: 'attrib_52',
                  ifDefaultValue: 'T',
                  isEdit: 'T',
                  isMake: 'C',
                  isNull: 'F',
                  orderId: '216',
                  showType: 'M',
                  tableName: 'prod_inst_ext',
                },
                {
                  attrId: '87658912',
                  attrLength: '100',
                  attrValueTypeId: '98M',
                  cname: '换漫游卡用户',
                  fieldName: 'attrib_51',
                  ifDefaultValue: 'N',
                  isEdit: 'T',
                  isMake: 'F',
                  isNull: 'T',
                  orderId: '370',
                  showType: 'M',
                  tableName: 'prod_inst_ext',
                },
                {
                  attrId: '1800999',
                  attrLength: '100',
                  attrValueTypeId: '98A',
                  cname: '是否CCG',
                  fieldName: 'attrib_36',
                  ifDefaultValue: 'T',
                  isEdit: 'T',
                  isMake: 'K',
                  isNull: 'T',
                  orderId: '291',
                  showType: 'M',
                  tableName: 'prod_inst_ext',
                },
                {
                  attrId: '8066',
                  attrLength: '255',
                  attrValueTypeId: '98M',
                  cname: '可选包',
                  colspan: '4',
                  fieldName: 'offer_inst_attr',
                  ifDefaultValue: '1',
                  isEdit: 'T',
                  isMake: 'T',
                  isNull: 'T',
                  makeField: '1',
                  orderId: '280',
                  pageField: '1',
                  showType: 'M',
                  tableName: 'prod_inst',
                },
                {
                  attrId: '10074',
                  attrLength: '100',
                  attrValueTypeId: '98M',
                  cname: '标准地址',
                  colspan: '3',
                  fieldName: 'address_desc',
                  isEdit: 'C',
                  isMake: 'F',
                  isNull: 'T',
                  orderId: '30',
                  pageField: 'XXXZ000000865100',
                  showType: 'M',
                  tableName: 'prod_inst',
                },
                {
                  attrId: '86',
                  attrLength: '100',
                  attrValueTypeId: '98D',
                  cname: '产品生效时间',
                  fieldName: 'attrib_33',
                  ifDefaultValue: 'N',
                  isEdit: 'T',
                  isMake: 'K',
                  isNull: 'T',
                  orderId: '125',
                  showType: 'M',
                  tableName: 'prod_inst_ext',
                },
                {
                  attrId: '20004',
                  attrLength: '100',
                  attrValueTypeId: '98D',
                  cname: '产品失效时间',
                  fieldName: 'attrib_34',
                  ifDefaultValue: 'N',
                  isEdit: 'T',
                  isMake: 'K',
                  isNull: 'T',
                  orderId: '125',
                  showType: 'M',
                  tableName: 'prod_inst_ext',
                },
                {
                  attrId: '16309',
                  attrLength: '100',
                  attrValueTypeId: '98C',
                  isNull: 'T',
                  cname: '销售模式',
                  fieldName: 'attrib_14',
                  isEdit: 'T',
                  isMake: 'C',
                  showType: 'M',
                  tableName: 'prod_inst_ext',
                },
                {
                  attrId: '60000196',
                  attrLength: '100',
                  attrValueTypeId: '98A',
                  cname: '续约标识',
                  defaultValue: '0',
                  fieldName: 'attrib_12',
                  ifDefaultValue: 'T',
                  isEdit: 'F',
                  isMake: 'T',
                  isNull: 'T',
                  orderId: '260',
                  showType: 'M',
                  tableName: 'prod_inst_ext',
                },
                {
                  attrId: '810000000',
                  attrValueTypeId: '98A',
                  cname: '4G标识',
                  fieldName: 'attrib_10',
                  isEdit: 'F',
                  isMake: 'F',
                  isNull: 'T',
                  showType: 'M',
                  tableName: 'prod_inst_ext',
                },
                {
                  attrId: '2301',
                  attrValueTypeId: '98M',
                  cname: '营销属性',
                  fieldName: 'attrib_21',
                  ifDefaultValue: 'N',
                  isEdit: 'T',
                  isMake: 'F',
                  isNull: 'F',
                  showType: 'M',
                  tableName: 'prod_inst_ext',
                },
                {
                  attrId: '2302',
                  attrValueTypeId: '98C',
                  cname: '赠送原因',
                  fieldName: 'attrib_22',
                  ifDefaultValue: 'N',
                  isEdit: 'C',
                  isMake: 'F',
                  isNull: 'F',
                  showType: 'M',
                  tableName: 'prod_inst_ext',
                },
                {
                  attrId: '10080',
                  attrLength: '32',
                  attrValueTypeId: 'FE',
                  cname: '产品密码',
                  fieldName: 'prod_inst_pwd',
                  ifDefaultValue: 'N',
                  isEdit: 'T',
                  isMake: 'T',
                  isNull: 'T',
                  orderId: '204',
                  showType: 'M',
                  tableName: 'prod_inst',
                },
                {
                  attrId: '10068',
                  attrLength: '100',
                  attrValueTypeId: 'HM',
                  isNull: 'T',
                  cname: '产品号码',
                  fieldName: 'acc_num',
                  isEdit: 'T',
                  isMake: 'K',
                  orderId: '100',
                  pageField: 'XXXH000000865100',
                  showType: 'D',
                  tableName: 'prod_inst',
                },
                {
                  attrId: '3100018',
                  attrLength: '100',
                  attrValueTypeId: '98A',
                  cname: '是否预开通',
                  defaultValue: '0',
                  fieldName: 'col2',
                  ifDefaultValue: 'T',
                  isEdit: 'T',
                  isMake: 'T',
                  isNull: 'T',
                  orderId: '113',
                  showType: 'M',
                  tableName: 'prod_inst',
                },
                {
                  attrId: '3023916',
                  attrLength: '100',
                  attrValueTypeId: 'K',
                  cname: 'UIM卡号',
                  isNull: 'T',
                  fieldName: 'col1',
                  isEdit: 'C',
                  isMake: 'K',
                  orderId: '110',
                  showType: 'D',
                  tableName: 'prod_inst',
                },
                {
                  attrId: '4000052',
                  attrLength: '100',
                  attrValueTypeId: '98A',
                  cname: '卡类型',
                  defaultValue: '1',
                  fieldName: 'col4',
                  isEdit: 'F',
                  isMake: 'T',
                  isNull: 'T',
                  orderId: '116',
                  showType: 'M',
                  tableName: 'prod_inst',
                },
                {
                  attrId: '11100739',
                  attrLength: '100',
                  attrValueTypeId: '98C',
                  cname: 'IMSI码',
                  fieldName: 'col5',
                  isEdit: 'F',
                  isMake: 'F',
                  isNull: 'T',
                  orderId: '121',
                  showType: 'M',
                  tableName: 'prod_inst',
                },
                {
                  attrId: '901033305',
                  attrLength: '100',
                  attrValueTypeId: '98A',
                  cname: '信用控制方式',
                  fieldName: 'col6',
                  ifDefaultValue: 'N',
                  isEdit: 'T',
                  isMake: 'F',
                  isNull: 'T',
                  orderId: '133',
                  showType: 'M',
                  tableName: 'prod_inst',
                },
                {
                  attrId: '13004',
                  attrLength: '100',
                  attrValueTypeId: '98A',
                  cname: '卡子类型',
                  fieldName: 'col7',
                  ifDefaultValue: 'N',
                  isEdit: 'F',
                  isMake: 'T',
                  isNull: 'T',
                  orderId: '119',
                  showType: 'M',
                  tableName: 'prod_inst',
                },
                {
                  attrId: '901033306',
                  attrLength: '100',
                  attrValueTypeId: '98A',
                  cname: '新信控标志',
                  fieldName: 'col8',
                  ifDefaultValue: 'N',
                  isEdit: 'T',
                  isMake: 'F',
                  isNull: 'T',
                  orderId: '136',
                  showType: 'M',
                  tableName: 'prod_inst',
                },
                {
                  attrFormat: '^\\d{0,4}$',
                  attrId: '999991346',
                  attrLength: '4',
                  attrValueTypeId: '98C',
                  cname: '初始信用额度',
                  defaultValue: '0',
                  fieldName: 'col9',
                  ifDefaultValue: 'T',
                  isEdit: 'F',
                  isMake: 'T',
                  isNull: 'T',
                  orderId: '122',
                  showType: 'M',
                  tableName: 'prod_inst',
                },
                {
                  attrId: '999991347',
                  attrLength: '100',
                  attrValueTypeId: '98C',
                  cname: '支付卡卡号',
                  fieldName: 'col10',
                  isEdit: 'F',
                  isMake: 'T',
                  isNull: 'T',
                  orderId: '125',
                  showType: 'M',
                  tableName: 'prod_inst',
                },
                {
                  attrId: '4000104',
                  attrLength: '100',
                  attrValueTypeId: '98A',
                  cname: '支付卡类型',
                  fieldName: 'col11',
                  ifDefaultValue: 'N',
                  isEdit: 'F',
                  isMake: 'T',
                  isNull: 'T',
                  orderId: '128',
                  showType: 'M',
                  tableName: 'prod_inst',
                },
                {
                  attrId: '999991348',
                  attrLength: '100',
                  attrValueTypeId: '98C',
                  cname: '联名卡卡号',
                  fieldName: 'col12',
                  isEdit: 'F',
                  isMake: 'T',
                  isNull: 'T',
                  orderId: '131',
                  showType: 'M',
                  tableName: 'prod_inst',
                },
                {
                  attrFormat: '^\\d{0,4}$',
                  attrId: '999991349',
                  attrLength: '100',
                  attrValueTypeId: '98C',
                  cname: '临时信用额度',
                  defaultValue: '0',
                  fieldName: 'col13',
                  ifDefaultValue: 'T',
                  isEdit: 'T',
                  isMake: 'K',
                  isNull: 'F',
                  orderId: '142',
                  showType: 'M',
                  tableName: 'prod_inst',
                },
                {
                  attrId: '999991350',
                  attrLength: '100',
                  attrValueTypeId: '98D',
                  isNull: 'T',
                  cname: '临时额度有效期',
                  fieldName: 'col14',
                  isEdit: 'F',
                  isMake: 'T',
                  orderId: '145',
                  showType: 'M',
                  tableName: 'prod_inst',
                },
                {
                  attrId: '999991351',
                  attrLength: '100',
                  attrValueTypeId: 'FP ',
                  cname: '绑定号码',
                  fieldName: 'col15',
                  isEdit: 'T',
                  isMake: 'F',
                  isNull: 'T',
                  orderId: '145',
                  showType: 'M',
                  tableName: 'prod_inst',
                },
                {
                  attrId: '999991352',
                  attrLength: '100',
                  attrValueTypeId: '98A',
                  cname: '绑定处理局',
                  fieldName: 'attrib_15',
                  ifDefaultValue: 'N',
                  isEdit: 'T',
                  isMake: 'F',
                  isNull: 'T',
                  orderId: '145',
                  showType: 'M',
                  tableName: 'prod_inst_ext',
                },
                {
                  attrId: '60000186',
                  attrLength: '100',
                  attrValueTypeId: '98A',
                  cname: '计费类型',
                  defaultValue: '0',
                  fieldName: 'attrib_16',
                  ifDefaultValue: 'T',
                  isEdit: 'T',
                  isMake: 'F',
                  isNull: 'F',
                  orderId: '148',
                  showType: 'M',
                  tableName: 'prod_inst_ext',
                },
                {
                  attrId: '999991353',
                  attrLength: '100',
                  attrValueTypeId: '98C',
                  cname: '审核编号',
                  fieldName: 'attrib_17',
                  isEdit: 'T',
                  isMake: 'K',
                  isNull: 'T',
                  orderId: '151',
                  showType: 'M',
                  tableName: 'prod_inst_ext',
                },
                {
                  attrId: '4000031',
                  attrLength: '100',
                  attrValueTypeId: '98D',
                  cname: '自动拆机日期',
                  fieldName: 'attrib_18',
                  isEdit: 'T',
                  isMake: 'K',
                  isNull: 'T',
                  orderId: '154',
                  showType: 'M',
                  tableName: 'prod_inst_ext',
                },
                {
                  attrId: '999991356',
                  attrLength: '100',
                  attrValueTypeId: '98A',
                  cname: '团购标识',
                  fieldName: 'attrib_20',
                  ifDefaultValue: 'N',
                  isEdit: 'T',
                  isMake: 'T',
                  isNull: 'T',
                  orderId: '265',
                  showType: 'M',
                  tableName: 'prod_inst_ext',
                },
                {
                  attrId: '11100656',
                  attrLength: '1000',
                  attrValueTypeId: '98M',
                  isNull: 'T',
                  cname: '帐户名称',
                  colspan: '3',
                  fieldName: 'prod_inst_acct_attr',
                  ifDefaultValue: 'T',
                  isEdit: 'T',
                  isMake: 'K',
                  orderId: '215',
                  showType: 'M',
                  tableName: 'prod_inst',
                },
                {
                  attrId: '10265',
                  attrValueTypeId: '98A',
                  cname: '产品性质',
                  defaultValue: '201',
                  fieldName: 'product_prop',
                  ifDefaultValue: 'T',
                  isEdit: 'F',
                  isMake: 'K',
                  isNull: 'T',
                  orderId: '210',
                  showType: 'M',
                  tableName: 'prod_inst',
                },
                {
                  attrId: '999991372',
                  attrLength: '100',
                  attrValueTypeId: '98A',
                  cname: '销账方式',
                  defaultValue: '0',
                  fieldName: 'bill_type',
                  isEdit: 'T',
                  isMake: 'T',
                  isNull: 'F',
                  orderId: '208',
                  showType: 'M',
                  tableName: 'prod_inst',
                },
                {
                  attrId: '999960014',
                  attrLength: '100',
                  attrValueTypeId: '98A',
                  cname: '卡商',
                  fieldName: 'attrib_23',
                  isEdit: 'T',
                  isMake: 'F',
                  isNull: 'T',
                  showType: 'M',
                  tableName: 'prod_inst_ext',
                },
                {
                  attrId: '999992890',
                  attrLength: '20',
                  attrValueTypeId: '98C',
                  cname: '翼支付余额',
                  colspan: '1',
                  fieldName: 'attrib_39',
                  ifDefaultValue: 'F',
                  isEdit: 'F',
                  isMake: 'K',
                  isNull: 'T',
                  orderId: '1',
                  showType: 'M',
                  tableName: 'prod_inst_ext',
                },
                {
                  attrId: '992074844',
                  attrLength: '255',
                  attrValueTypeId: '98M',
                  cname: '经办人客户名称',
                  fieldName: 'attrib_27',
                  isEdit: 'F',
                  isMake: 'T',
                  isNull: 'T',
                  orderId: '100',
                  showType: 'M',
                  tableName: 'prod_inst_ext',
                },
                {
                  attrId: '14072103',
                  attrLength: '100',
                  attrValueTypeId: '98M',
                  cname: '所属网格',
                  colspan: '1',
                  fieldName: 'attrib_09',
                  isEdit: 'C',
                  isMake: 'T',
                  isNull: 'T',
                  orderId: '288',
                  showType: 'M',
                  tableName: 'prod_inst_ext',
                },
                {
                  attrId: '130000473',
                  attrLength: '10',
                  attrValueTypeId: '98A',
                  cname: '是否IDC业务发展',
                  defaultValue: '2',
                  fieldName: 'attrib_24',
                  ifDefaultValue: 'T',
                  isEdit: 'T',
                  isMake: 'T',
                  isNull: 'T',
                  orderId: '102',
                  showType: 'M',
                  tableName: 'prod_inst_ext',
                },
                {
                  attrId: '20140608',
                  attrLength: '100',
                  attrValueTypeId: '98C',
                  cname: '揽收人',
                  fieldName: 'attrib_01',
                  ifDefaultValue: 'F',
                  isEdit: 'T',
                  isMake: 'F',
                  isNull: 'T',
                  orderId: '112',
                  showType: 'M',
                  tableName: 'prod_inst_ext',
                },
                {
                  attrId: '150409161',
                  attrLength: '255',
                  attrValueTypeId: '98M',
                  cname: '责任人',
                  fieldName: 'col3',
                  isEdit: 'F',
                  isMake: 'F',
                  isNull: 'T',
                  orderId: '100',
                  showType: 'M',
                  tableName: 'prod_inst',
                },
                {
                  attrId: '150409162',
                  attrLength: '10',
                  attrValueTypeId: '98A',
                  cname: '是否物用卡',
                  defaultValue: '2',
                  fieldName: 'attrib_02',
                  ifDefaultValue: 'T',
                  isEdit: 'F',
                  isMake: 'T',
                  isNull: 'T',
                  orderId: '102',
                  showType: 'M',
                  tableName: 'prod_inst_ext',
                },
                {
                  attrId: '150806162',
                  attrLength: '100',
                  attrValueTypeId: '98M',
                  cname: '短信验证码',
                  fieldName: 'attrib_03',
                  isEdit: 'T',
                  isMake: 'K',
                  isNull: 'T',
                  orderId: '292',
                  showType: 'M',
                  tableName: 'prod_inst_ext',
                },
                {
                  attrId: '901033309',
                  attrLength: '100',
                  attrValueTypeId: '98A',
                  cname: '是否核对一证五卡信息',
                  defaultValue: '0',
                  fieldName: 'attrib_37',
                  ifDefaultValue: 'T',
                  isEdit: 'F',
                  isMake: 'T',
                  isNull: 'T',
                  orderId: '102',
                  showType: 'M',
                  tableName: 'prod_inst_ext',
                },
                {
                  attrId: '2147483647',
                  attrLength: '255',
                  attrValueTypeId: '98M',
                  cname: '集团责任人',
                  fieldName: 'attrib_04',
                  isEdit: 'F',
                  isMake: 'T',
                  isNull: 'T',
                  orderId: '100',
                  showType: 'M',
                  tableName: 'prod_inst_ext',
                },
                {
                  attrId: '703011931',
                  attrLength: '255',
                  attrValueTypeId: '98A',
                  cname: '实名登记类型',
                  defaultValue: '10',
                  fieldName: 'attrib_05',
                  ifDefaultValue: 'T',
                  isEdit: 'F',
                  isMake: 'F',
                  isNull: 'T',
                  orderId: '100',
                  showType: 'M',
                  tableName: 'prod_inst_ext',
                },
              ],
            },
            prodFunc: {
              isShow: 'T',
              moduleId: '8',
              moduleName: '功能产品组件',
              orderId: '1',
              prodFuncList: [
                {
                  prodId: '12',
                  prodInstId: '34545',
                  prodName: '来电显示',
                  selected: 'T',
                },
                {
                  prodId: '123',
                  prodInstId: '345453',
                  prodName: '彩铃',
                  selected: 'T',
                },
              ],
            },
            prodInstId: '343443',
            prodRoleId: '70000003',
            prodRoleName: '移动电话',
            prodSubOffer: {
              isShow: 'T',
              moduleId: '7',
              moduleName: '可选包产品组件',
              orderId: '1',
              prodSubOfferTypeList: [
                {
                  prodSubOfferList: [
                    {
                      offerId: '1',
                      offerName: 'X元预存充值（账户级）',
                    },
                    {
                      offerId: '2',
                      offerName: '2016-乐享4G套餐8折促销',
                    },
                  ],
                  rstrType: '1200',
                  rstrTypeDesc: '必选',
                },
                {
                  prodSubOfferList: [
                    {
                      offerId: '4',
                      offerName: '乐享4G合约计划-',
                    },
                    {
                      offerId: '5',
                      offerName: 'iPhone 8 终端补贴',
                      rstrMktRes: true,
                    },
                  ],
                  rstrType: '1300',
                  rstrTypeDesc: '缺省',
                },
              ],
            },
          },
          {
            deleteFlag: 'true',
            isShow: 'T',
            maxNum: '10',
            minNum: '1',
            mktRes: {
              isShow: 'F',
              moduleId: '9',
              moduleName: '终端组件',
              orderId: '1',
            },
            moduleId: '3',
            moduleName: '加装手机',
            orderId: '1',
            prodAttr: {
              prodAttrList: [
                {
                  attrId: '992075366',
                  attrLength: '255',
                  attrValueTypeId: '98M',
                  cname: '预存款充值',
                  colspan: '1',
                  fieldName: 'attrib_32',
                  isEdit: 'C',
                  isMake: 'T',
                  isNull: 'T',
                  orderId: '12',
                  showType: 'M',
                  tableName: 'prod_inst_ext',
                },
                {
                  attrId: '9998066',
                  attrLength: '255',
                  attrValueTypeId: '98M',
                  cname: '关联产品',
                  colspan: '2',
                  fieldName: 'prod_inst_rela_attr',
                  ifDefaultValue: 'N',
                  isEdit: 'T',
                  isMake: 'C',
                  isNull: 'T',
                  orderId: '270',
                  showType: 'M',
                  tableName: 'prod_inst',
                },
                {
                  attrId: '1020161',
                  attrLength: '100',
                  attrValueTypeId: '98A',
                  cname: '是否开通信控',
                  defaultValue: '2',
                  fieldName: 'attrib_26',
                  ifDefaultValue: 'T',
                  isEdit: 'T',
                  isMake: 'T',
                  isNull: 'T',
                  orderId: '130',
                  showType: 'M',
                  tableName: 'prod_inst_ext',
                },
                {
                  attrId: '1351001',
                  attrLength: '100',
                  attrValueTypeId: '98A',
                  cname: '成品卡批开状态',
                  fieldName: 'attrib_40',
                  ifDefaultValue: 'N',
                  isEdit: 'T',
                  isMake: 'F',
                  isNull: 'T',
                  orderId: '2',
                  showType: 'M',
                  tableName: 'prod_inst_ext',
                },
                {
                  attrId: '690000311',
                  attrLength: '10000',
                  attrValueTypeId: '98M',
                  cname: '扩展产品',
                  colspan: '4',
                  fieldName: 'sub_prod_inst_attr',
                  isEdit: 'T',
                  isMake: 'K',
                  isNull: 'T',
                  orderId: '72',
                  showType: 'M',
                  tableName: 'prod_inst',
                },
                {
                  attrId: '1413001',
                  attrLength: '100',
                  attrValueTypeId: '98A',
                  cname: '4G用户标识',
                  defaultValue: '0',
                  fieldName: 'attrib_19',
                  ifDefaultValue: 'F',
                  isEdit: 'T',
                  isMake: 'F',
                  isNull: 'F',
                  orderId: '148',
                  showType: 'M',
                  tableName: 'prod_inst_ext',
                },
                {
                  attrId: '692303202',
                  attrLength: '10',
                  attrValueTypeId: '98A',
                  cname: '是否准预',
                  defaultValue: '2000',
                  fieldName: 'attrib_52',
                  ifDefaultValue: 'T',
                  isEdit: 'T',
                  isMake: 'C',
                  isNull: 'F',
                  orderId: '216',
                  showType: 'M',
                  tableName: 'prod_inst_ext',
                },
                {
                  attrId: '87658912',
                  attrLength: '100',
                  attrValueTypeId: '98M',
                  cname: '换漫游卡用户',
                  fieldName: 'attrib_51',
                  ifDefaultValue: 'N',
                  isEdit: 'T',
                  isMake: 'F',
                  isNull: 'T',
                  orderId: '370',
                  showType: 'M',
                  tableName: 'prod_inst_ext',
                },
                {
                  attrId: '1800999',
                  attrLength: '100',
                  attrValueTypeId: '98A',
                  cname: '是否CCG',
                  fieldName: 'attrib_36',
                  ifDefaultValue: 'T',
                  isEdit: 'T',
                  isMake: 'K',
                  isNull: 'T',
                  orderId: '291',
                  showType: 'M',
                  tableName: 'prod_inst_ext',
                },
                {
                  attrId: '8066',
                  attrLength: '255',
                  attrValueTypeId: '98M',
                  cname: '可选包',
                  colspan: '4',
                  fieldName: 'offer_inst_attr',
                  ifDefaultValue: '1',
                  isEdit: 'T',
                  isMake: 'T',
                  isNull: 'T',
                  makeField: '1',
                  orderId: '280',
                  pageField: '1',
                  showType: 'M',
                  tableName: 'prod_inst',
                },
                {
                  attrId: '10074',
                  attrLength: '100',
                  attrValueTypeId: '98M',
                  cname: '标准地址',
                  colspan: '3',
                  fieldName: 'address_desc',
                  isEdit: 'C',
                  isMake: 'F',
                  isNull: 'T',
                  orderId: '30',
                  pageField: 'XXXZ000000865100',
                  showType: 'M',
                  tableName: 'prod_inst',
                },
                {
                  attrId: '86',
                  attrLength: '100',
                  attrValueTypeId: '98D',
                  cname: '产品生效时间',
                  fieldName: 'attrib_33',
                  ifDefaultValue: 'N',
                  isEdit: 'T',
                  isMake: 'K',
                  isNull: 'T',
                  orderId: '125',
                  showType: 'M',
                  tableName: 'prod_inst_ext',
                },
                {
                  attrId: '20004',
                  attrLength: '100',
                  attrValueTypeId: '98D',
                  cname: '产品失效时间',
                  fieldName: 'attrib_34',
                  ifDefaultValue: 'N',
                  isEdit: 'T',
                  isMake: 'K',
                  isNull: 'T',
                  orderId: '125',
                  showType: 'M',
                  tableName: 'prod_inst_ext',
                },
                {
                  attrId: '16309',
                  attrLength: '100',
                  attrValueTypeId: '98C',
                  cname: '销售模式',
                  fieldName: 'attrib_14',
                  isEdit: 'T',
                  isMake: 'C',
                  isNull: 'T',
                  showType: 'M',
                  tableName: 'prod_inst_ext',
                },
                {
                  attrId: '60000196',
                  attrLength: '100',
                  attrValueTypeId: '98A',
                  cname: '续约标识',
                  defaultValue: '0',
                  fieldName: 'attrib_12',
                  ifDefaultValue: 'T',
                  isEdit: 'F',
                  isMake: 'T',
                  isNull: 'T',
                  orderId: '260',
                  showType: 'M',
                  tableName: 'prod_inst_ext',
                },
                {
                  attrId: '810000000',
                  attrValueTypeId: '98A',
                  cname: '4G标识',
                  fieldName: 'attrib_10',
                  isEdit: 'F',
                  isMake: 'F',
                  isNull: 'T',
                  showType: 'M',
                  tableName: 'prod_inst_ext',
                },
                {
                  attrId: '2301',
                  attrValueTypeId: '98M',
                  cname: '营销属性',
                  fieldName: 'attrib_21',
                  ifDefaultValue: 'N',
                  isEdit: 'T',
                  isMake: 'F',
                  isNull: 'F',
                  showType: 'M',
                  tableName: 'prod_inst_ext',
                },
                {
                  attrId: '2302',
                  attrValueTypeId: '98C',
                  cname: '赠送原因',
                  fieldName: 'attrib_22',
                  ifDefaultValue: 'N',
                  isEdit: 'C',
                  isMake: 'F',
                  isNull: 'F',
                  showType: 'M',
                  tableName: 'prod_inst_ext',
                },
                {
                  attrId: '10080',
                  attrLength: '32',
                  attrValueTypeId: 'FE',
                  cname: '产品密码',
                  fieldName: 'prod_inst_pwd',
                  ifDefaultValue: 'N',
                  isEdit: 'T',
                  isMake: 'T',
                  isNull: 'T',
                  orderId: '204',
                  showType: 'M',
                  tableName: 'prod_inst',
                },
                {
                  attrId: '10068',
                  attrLength: '100',
                  attrValueTypeId: 'HM',
                  cname: '产品号码',
                  fieldName: 'acc_num',
                  isEdit: 'T',
                  isMake: 'K',
                  isNull: 'F',
                  orderId: '100',
                  pageField: 'XXXH000000865100',
                  showType: 'D',
                  tableName: 'prod_inst',
                },
                {
                  attrId: '3100018',
                  attrLength: '100',
                  attrValueTypeId: '98A',
                  cname: '是否预开通',
                  defaultValue: '0',
                  fieldName: 'col2',
                  ifDefaultValue: 'T',
                  isEdit: 'T',
                  isMake: 'T',
                  isNull: 'T',
                  orderId: '113',
                  showType: 'M',
                  tableName: 'prod_inst',
                },
                {
                  attrId: '3023916',
                  attrLength: '100',
                  attrValueTypeId: 'K',
                  cname: 'UIM卡号',
                  fieldName: 'col1',
                  isEdit: 'C',
                  isMake: 'K',
                  isNull: 'F',
                  orderId: '110',
                  showType: 'D',
                  tableName: 'prod_inst',
                },
                {
                  attrId: '4000052',
                  attrLength: '100',
                  attrValueTypeId: '98A',
                  cname: '卡类型',
                  defaultValue: '1',
                  fieldName: 'col4',
                  isEdit: 'F',
                  isMake: 'T',
                  isNull: 'T',
                  orderId: '116',
                  showType: 'M',
                  tableName: 'prod_inst',
                },
                {
                  attrId: '11100739',
                  attrLength: '100',
                  attrValueTypeId: '98C',
                  cname: 'IMSI码',
                  fieldName: 'col5',
                  isEdit: 'F',
                  isMake: 'F',
                  isNull: 'T',
                  orderId: '121',
                  showType: 'M',
                  tableName: 'prod_inst',
                },
                {
                  attrId: '901033305',
                  attrLength: '100',
                  attrValueTypeId: '98A',
                  cname: '信用控制方式',
                  fieldName: 'col6',
                  ifDefaultValue: 'N',
                  isEdit: 'T',
                  isMake: 'F',
                  isNull: 'T',
                  orderId: '133',
                  showType: 'M',
                  tableName: 'prod_inst',
                },
                {
                  attrId: '13004',
                  attrLength: '100',
                  attrValueTypeId: '98A',
                  cname: '卡子类型',
                  fieldName: 'col7',
                  ifDefaultValue: 'N',
                  isEdit: 'F',
                  isMake: 'T',
                  isNull: 'T',
                  orderId: '119',
                  showType: 'M',
                  tableName: 'prod_inst',
                },
                {
                  attrId: '901033306',
                  attrLength: '100',
                  attrValueTypeId: '98A',
                  cname: '新信控标志',
                  fieldName: 'col8',
                  ifDefaultValue: 'N',
                  isEdit: 'T',
                  isMake: 'F',
                  isNull: 'T',
                  orderId: '136',
                  showType: 'M',
                  tableName: 'prod_inst',
                },
                {
                  attrFormat: '^\\d{0,4}$',
                  attrId: '999991346',
                  attrLength: '4',
                  attrValueTypeId: '98C',
                  cname: '初始信用额度',
                  defaultValue: '0',
                  fieldName: 'col9',
                  ifDefaultValue: 'T',
                  isEdit: 'F',
                  isMake: 'T',
                  isNull: 'T',
                  orderId: '122',
                  showType: 'M',
                  tableName: 'prod_inst',
                },
                {
                  attrId: '999991347',
                  attrLength: '100',
                  attrValueTypeId: '98C',
                  cname: '支付卡卡号',
                  fieldName: 'col10',
                  isEdit: 'F',
                  isMake: 'T',
                  isNull: 'T',
                  orderId: '125',
                  showType: 'M',
                  tableName: 'prod_inst',
                },
                {
                  attrId: '4000104',
                  attrLength: '100',
                  attrValueTypeId: '98A',
                  cname: '支付卡类型',
                  fieldName: 'col11',
                  ifDefaultValue: 'N',
                  isEdit: 'F',
                  isMake: 'T',
                  isNull: 'T',
                  orderId: '128',
                  showType: 'M',
                  tableName: 'prod_inst',
                },
                {
                  attrId: '999991348',
                  attrLength: '100',
                  attrValueTypeId: '98C',
                  cname: '联名卡卡号',
                  fieldName: 'col12',
                  isEdit: 'F',
                  isMake: 'T',
                  isNull: 'T',
                  orderId: '131',
                  showType: 'M',
                  tableName: 'prod_inst',
                },
                {
                  attrFormat: '^\\d{0,4}$',
                  attrId: '999991349',
                  attrLength: '100',
                  attrValueTypeId: '98C',
                  cname: '临时信用额度',
                  defaultValue: '0',
                  fieldName: 'col13',
                  ifDefaultValue: 'T',
                  isEdit: 'T',
                  isMake: 'K',
                  isNull: 'F',
                  orderId: '142',
                  showType: 'M',
                  tableName: 'prod_inst',
                },
                {
                  attrId: '999991350',
                  attrLength: '100',
                  attrValueTypeId: '98D',
                  cname: '临时额度有效期',
                  fieldName: 'col14',
                  isEdit: 'F',
                  isMake: 'T',
                  isNull: 'T',
                  orderId: '145',
                  showType: 'M',
                  tableName: 'prod_inst',
                },
                {
                  attrId: '999991351',
                  attrLength: '100',
                  attrValueTypeId: 'FP ',
                  cname: '绑定号码',
                  fieldName: 'col15',
                  isEdit: 'T',
                  isMake: 'F',
                  isNull: 'T',
                  orderId: '145',
                  showType: 'M',
                  tableName: 'prod_inst',
                },
                {
                  attrId: '999991352',
                  attrLength: '100',
                  attrValueTypeId: '98A',
                  cname: '绑定处理局',
                  fieldName: 'attrib_15',
                  ifDefaultValue: 'N',
                  isEdit: 'T',
                  isMake: 'F',
                  isNull: 'T',
                  orderId: '145',
                  showType: 'M',
                  tableName: 'prod_inst_ext',
                },
                {
                  attrId: '60000186',
                  attrLength: '100',
                  attrValueTypeId: '98A',
                  cname: '计费类型',
                  defaultValue: '0',
                  fieldName: 'attrib_16',
                  ifDefaultValue: 'T',
                  isEdit: 'T',
                  isMake: 'F',
                  isNull: 'F',
                  orderId: '148',
                  showType: 'M',
                  tableName: 'prod_inst_ext',
                },
                {
                  attrId: '999991353',
                  attrLength: '100',
                  attrValueTypeId: '98C',
                  cname: '审核编号',
                  fieldName: 'attrib_17',
                  isEdit: 'T',
                  isMake: 'K',
                  isNull: 'T',
                  orderId: '151',
                  showType: 'M',
                  tableName: 'prod_inst_ext',
                },
                {
                  attrId: '4000031',
                  attrLength: '100',
                  attrValueTypeId: '98D',
                  cname: '自动拆机日期',
                  fieldName: 'attrib_18',
                  isEdit: 'T',
                  isMake: 'K',
                  isNull: 'T',
                  orderId: '154',
                  showType: 'M',
                  tableName: 'prod_inst_ext',
                },
                {
                  attrId: '999991356',
                  attrLength: '100',
                  attrValueTypeId: '98A',
                  cname: '团购标识',
                  fieldName: 'attrib_20',
                  ifDefaultValue: 'N',
                  isEdit: 'T',
                  isMake: 'T',
                  isNull: 'T',
                  orderId: '265',
                  showType: 'M',
                  tableName: 'prod_inst_ext',
                },
                {
                  attrId: '11100656',
                  attrLength: '1000',
                  attrValueTypeId: '98M',
                  cname: '帐户名称',
                  colspan: '3',
                  fieldName: 'prod_inst_acct_attr',
                  ifDefaultValue: 'T',
                  isEdit: 'T',
                  isMake: 'K',
                  isNull: 'F',
                  orderId: '215',
                  showType: 'M',
                  tableName: 'prod_inst',
                },
                {
                  attrId: '10265',
                  attrValueTypeId: '98A',
                  cname: '产品性质',
                  defaultValue: '201',
                  fieldName: 'product_prop',
                  ifDefaultValue: 'T',
                  isEdit: 'F',
                  isMake: 'K',
                  isNull: 'T',
                  orderId: '210',
                  showType: 'M',
                  tableName: 'prod_inst',
                },
                {
                  attrId: '999991372',
                  attrLength: '100',
                  attrValueTypeId: '98A',
                  cname: '销账方式',
                  defaultValue: '0',
                  fieldName: 'bill_type',
                  isEdit: 'T',
                  isMake: 'T',
                  isNull: 'F',
                  orderId: '208',
                  showType: 'M',
                  tableName: 'prod_inst',
                },
                {
                  attrId: '999960014',
                  attrLength: '100',
                  attrValueTypeId: '98A',
                  cname: '卡商',
                  fieldName: 'attrib_23',
                  isEdit: 'T',
                  isMake: 'F',
                  isNull: 'T',
                  showType: 'M',
                  tableName: 'prod_inst_ext',
                },
                {
                  attrId: '999992890',
                  attrLength: '20',
                  attrValueTypeId: '98C',
                  cname: '翼支付余额',
                  colspan: '1',
                  fieldName: 'attrib_39',
                  ifDefaultValue: 'F',
                  isEdit: 'F',
                  isMake: 'K',
                  isNull: 'T',
                  orderId: '1',
                  showType: 'M',
                  tableName: 'prod_inst_ext',
                },
                {
                  attrId: '992074844',
                  attrLength: '255',
                  attrValueTypeId: '98M',
                  cname: '经办人客户名称',
                  fieldName: 'attrib_27',
                  isEdit: 'F',
                  isMake: 'T',
                  isNull: 'T',
                  orderId: '100',
                  showType: 'M',
                  tableName: 'prod_inst_ext',
                },
                {
                  attrId: '14072103',
                  attrLength: '100',
                  attrValueTypeId: '98M',
                  cname: '所属网格',
                  colspan: '1',
                  fieldName: 'attrib_09',
                  isEdit: 'C',
                  isMake: 'T',
                  isNull: 'T',
                  orderId: '288',
                  showType: 'M',
                  tableName: 'prod_inst_ext',
                },
                {
                  attrId: '130000473',
                  attrLength: '10',
                  attrValueTypeId: '98A',
                  cname: '是否IDC业务发展',
                  defaultValue: '2',
                  fieldName: 'attrib_24',
                  ifDefaultValue: 'T',
                  isEdit: 'T',
                  isMake: 'T',
                  isNull: 'T',
                  orderId: '102',
                  showType: 'M',
                  tableName: 'prod_inst_ext',
                },
                {
                  attrId: '20140608',
                  attrLength: '100',
                  attrValueTypeId: '98C',
                  cname: '揽收人',
                  fieldName: 'attrib_01',
                  ifDefaultValue: 'F',
                  isEdit: 'T',
                  isMake: 'F',
                  isNull: 'T',
                  orderId: '112',
                  showType: 'M',
                  tableName: 'prod_inst_ext',
                },
                {
                  attrId: '150409161',
                  attrLength: '255',
                  attrValueTypeId: '98M',
                  cname: '责任人',
                  fieldName: 'col3',
                  isEdit: 'F',
                  isMake: 'F',
                  isNull: 'T',
                  orderId: '100',
                  showType: 'M',
                  tableName: 'prod_inst',
                },
                {
                  attrId: '150409162',
                  attrLength: '10',
                  attrValueTypeId: '98A',
                  cname: '是否物用卡',
                  defaultValue: '2',
                  fieldName: 'attrib_02',
                  ifDefaultValue: 'T',
                  isEdit: 'F',
                  isMake: 'T',
                  isNull: 'T',
                  orderId: '102',
                  showType: 'M',
                  tableName: 'prod_inst_ext',
                },
                {
                  attrId: '150806162',
                  attrLength: '100',
                  attrValueTypeId: '98M',
                  cname: '短信验证码',
                  fieldName: 'attrib_03',
                  isEdit: 'T',
                  isMake: 'K',
                  isNull: 'T',
                  orderId: '292',
                  showType: 'M',
                  tableName: 'prod_inst_ext',
                },
                {
                  attrId: '901033309',
                  attrLength: '100',
                  attrValueTypeId: '98A',
                  cname: '是否核对一证五卡信息',
                  defaultValue: '0',
                  fieldName: 'attrib_37',
                  ifDefaultValue: 'T',
                  isEdit: 'F',
                  isMake: 'T',
                  isNull: 'T',
                  orderId: '102',
                  showType: 'M',
                  tableName: 'prod_inst_ext',
                },
                {
                  attrId: '2147483647',
                  attrLength: '255',
                  attrValueTypeId: '98M',
                  cname: '集团责任人',
                  fieldName: 'attrib_04',
                  isEdit: 'F',
                  isMake: 'T',
                  isNull: 'T',
                  orderId: '100',
                  showType: 'M',
                  tableName: 'prod_inst_ext',
                },
                {
                  attrId: '703011931',
                  attrLength: '255',
                  attrValueTypeId: '98A',
                  cname: '实名登记类型',
                  defaultValue: '10',
                  fieldName: 'attrib_05',
                  ifDefaultValue: 'T',
                  isEdit: 'F',
                  isMake: 'F',
                  isNull: 'T',
                  orderId: '100',
                  showType: 'M',
                  tableName: 'prod_inst_ext',
                },
              ],
            },
            prodFunc: {
              isShow: 'T',
              moduleId: '8',
              moduleName: '功能产品组件',
              orderId: '1',
              prodFuncList: [
                {
                  prodId: '12',
                  prodInstId: '34545',
                  prodName: '来电显示',
                  selected: 'T',
                },
                {
                  prodId: '123',
                  prodInstId: '345453',
                  prodName: '彩铃',
                  selected: 'T',
                },
              ],
            },
            prodInstId: '343443',
            prodRoleId: '71000003',
            prodRoleName: '加装手机',
            prodSubOffer: {
              isShow: 'T',
              moduleId: '7',
              moduleName: '可选包产品组件',
              orderId: '1',
              prodSubOfferTypeList: [
                {
                  prodSubOfferList: [
                    {
                      offerId: '1',
                      offerName: 'X元预存充值（账户级）',
                    },
                    {
                      offerId: '2',
                      offerName: '2016-乐享4G套餐8折促销',
                    },
                  ],
                  rstrType: '1200',
                  rstrTypeDesc: '必选',
                },
                {
                  prodSubOfferList: [
                    {
                      offerId: '4',
                      offerName: '乐享4G合约计划-',
                    },
                    {
                      offerId: '5',
                      offerName: 'iPhone 8 终端补贴',
                      rstrMktRes: true,
                    },
                  ],
                  rstrType: '1300',
                  rstrTypeDesc: '缺省',
                },
              ],
            },
          },
        ],
        roleButton: [
          {
            buttonName: '加装手机',
            currentNum: '1',
            maxNum: '10',
            prodRoleId: '71000003',
          },
        ],
      },
    ],
    sceneInstId: '1bf555f89d5546d6aaa3e002aacc0bc4',
    sceneName: '办理新装',
    templateId: '1',
  },
};
